# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: /13141516.github.io
description: "I graduated from University of Chinese Academy of Sciences as Master Degree in computer technology. In the past I participate in the development of many projects like Java, C/C, phython and so on.When I see Data Contest and Machine Learning, I am addicted to it. So now I decide to do it with every who want to do Machine Learning!"
email: chuzhouchenli@163.com
github_username: chenli
markdown: kramdown
title: "chale chen"
twitter_username: chenli
url: "https://github.com/13141516/"

# Build settings
markdown: kramdown
